import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link"
import { ThemeSwitcher } from "@/components/theme-switcher";
import { ThemeProvider } from "next-themes";
import { hasEnvVars } from "@/utils/supabase/check-env-vars";
import HeaderAuth from "@/components/header-auth";

import { Bell, Home, Search, User, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import DeployButton from "@/components/deploy-button";
import { EnvVarWarning } from "@/components/env-var-warning";

import { Toaster } from "@/components/ui/toaster"


// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col min-h-screen ">

            <header className="flex items-center justify-between p-4 bg-white border-b">
                <h1 className="text-2xl font-bold">SimpanResit</h1>
                <div className="flex items-center gap-4">
                    {/* <Button variant="ghost" size="icon" aria-label="Search">
                            <Search className="w-5 h-5" />
                        </Button>
                        <Button variant="ghost" size="icon" aria-label="Notifications">
                            <Bell className="w-5 h-5" />
                        </Button> */}
                    {/* {!hasEnvVars ? <EnvVarWarning /> : <HeaderAuth />} */}

                </div>
            </header>
            {children}
            <Toaster />
            <div className="p-10"></div>
            <footer className="fixed bottom-0 w-full grid grid-cols-3 p-4 bg-white border-t">
                <Link
                    href="/protected/dashboard"
                    className="flex flex-col items-center gap-1 text-sm font-medium text-muted-foreground"
                    aria-label="Home"
                >
                    <Home className="w-5 h-5" />
                    <span>Home</span>
                </Link>
                <Link
                    href="/protected/receipts"
                    className="flex flex-col items-center gap-1 text-sm font-medium text-primary"
                    aria-label="Receipts"
                >
                    <Upload className="w-5 h-5" />
                    <span>Receipts</span>
                </Link>
                <Link
                    href="/protected/profile"
                    className="flex flex-col items-center gap-1 text-sm font-medium text-muted-foreground"
                    aria-label="Profile"
                >
                    <User className="w-5 h-5" />
                    <span>Profile</span>
                </Link>
            </footer>
        </div>
    );
}
