import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"
import { ThemeSwitcher } from "@/components/theme-switcher";
import { ThemeProvider } from "next-themes";
import { hasEnvVars } from "@/utils/supabase/check-env-vars";
import HeaderAuth from "@/components/header-auth";

import { Bell, Home, Search, User, Upload } from "lucide-react"
import { Button } from "@/components/ui/button"
import DeployButton from "@/components/deploy-button";
import { EnvVarWarning } from "@/components/env-var-warning";

import { Toaster } from "@/components/ui/toaster"

import "./globals.css";

// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {/* <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                > */}

                {children}
                <Toaster />


                {/* </ThemeProvider> */}

            </body>
        </html >
    );
}
